version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: dotnet --version
- cmd: dotnet restore ./Source/Windsor.Extension.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: gitlink . -c Debug
deploy:
- provider: NuGet
  server: https://www.myget.org/F/windsor-extension/api/v2/package
  symbol_server: https://www.myget.org/F/windsor-extension/symbols/api/v2/package
  api_key:
    secure: qco32qivabmt7WfK9zMUWvF2fp9kgk3c7A9ZUu23rvwiXxy1dzS+DjssfBaz15sA
  artifact: /.*\.nupkg/  
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cinst gitlink -y
